import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        {/*
        1. The home page should have a search bar where users can enter keywords to search for recipes. 
        2. The search results should display recipe cards with each recipe's name, image, and brief description. 
        3. Users can click on a recipe card to view the full recipe details, including the ingredients and instructions.
        4. Users can save their favorite recipes to a bookmark list. 
        5. The bookmark list should be displayed on a separate page, with each saved recipe displayed as a card with the name and image of the recipe.
        6. Users can remove a saved recipe from the bookmark list by clicking on a "Remove" button on the recipe card.
        7. The web app should have a responsive design and be accessible.
        */}
      </main>
    </>
  )
}
